import React from 'react';
import { Blog } from '../../components';

export default function melissa_kang() {
    return (
        <Blog.TextBlock>
            <Blog.Author>Interviewed and Written by Sarah Jackson</Blog.Author>
            <br />
            <br />
            <Blog.Text><em>For a generation of teenage girls, Dolly Doctor answered anxious questions about bodies, puberty and sexual health. Dr Melissa Kang (MBBS MCH PhD) is a GP and academic, and is passionate about young people and sexual health. She works part time as a medical officer in western Sydney with homeless and marginalised young people. She is an Associate Professor in Public Health at the University of Technology Sydney. Melissa’s research has focused on young people’s sexuality, sexual health, and access to health care. She is currently the president of the Australian Association for Adolescent Health, and was “Dolly Doctor” for 23 years before Dolly Magazine closed in December 2016.</em></Blog.Text>
            <br />
            <br />
            <Blog.Subtitle>~FROM PAEDIATRICS TRAINEE, TO GP TRAINEE, TO DOLLY DOCTOR~</Blog.Subtitle>
            <Blog.Text>The advice I was given was that I would have to study paediatrics as a pathway into adolescent medicine. By the end of that first year of unaccredited paediatric training, I became pregnant with my first child. I defaulted back to general practice as it was the only speciality you could do part-time. I actually really enjoyed it. I found the variety and the kinds of things you could do in primary care much more comprehensive and intersectional. I almost completed general practice training which included a term and a half of special skills in adolescent medicine. Then a position became available for a GP in a multidisciplinary primary care health service that looked after homeless young people. I decided to apply for that. I was told by the college and GPs that I had already done too much adolescent medicine in my GP training, and that I would have to decide whether to stop short of completing GP training. I made that decision and I stuck with this job in a youth health service. Later I was offered a position in the department of Adolescent Medicine at The Children’s Hospital in Sydney. I ended up becoming a clinician in a specialty service, even though I was not trained as a paediatrician. I was incredibly lucky. I did the same clinics as the paediatricians - patients with chronic and complex illnesses like eating disorders. The only difference was that I didn’t have any admitting rights. I felt like I’d landed my dream job really. I was granted vocational registration, so I call myself a GP but I’m not really a GP. It is a bit like adolescence - I’m not quite sure who I am. </Blog.Text>
            <Blog.Text>Way back in 1993, when I was still working as a GP registrar in the special skills adolescent medicine post, I met a GP who was answering questions for Dolly Doctor. She was one of a series of GPs who belonged to the New South Wales Association for Adolescent Health. They had been contracted by Dolly Magazine to use their medical members to answer questions. She would sometimes ask me what I thought and if I’d like to answer some. Then after a few months, she asked would I be interested in taking over. I grabbed it and for 23 years I never let go.</Blog.Text>
            <br />
            <br />
            <Blog.Subtitle>~BEING DOLLY DOCTOR~</Blog.Subtitle>
            <Blog.Text>It was not a huge amount of work each month, but I really, really loved it. I would labour over every single question. I would look up textbooks. I would ring up specialists to help me make sure I had everything absolutely right. It felt like a huge responsibility. You couldn’t afford to get anything wrong. Sometimes I would share some questions around the table at work with the multidisciplinary team I was working with. I had fantastic advice and suggestions from some of my allied health and social worker colleagues. They were really good at taking a very holistic approach to answering the question. </Blog.Text>
            <Blog.Text>It was a real interaction between a readership and a magazine. They didn’t know who I was. I was semi-anonymous. They just had my first name. It was this weird Twilight Zone, I guess.  It was a really interesting and challenging way of interacting with the same population I was working with clinically. There was this outpouring of concerns, desperation, anxiety, guilt and sometimes shame from readers to this trusted source of Dolly Doctor. So I was just trying to address whatever it was and normalize it, or put it into context. Then I would also try and see if there were any resources. Back in those days there were no websites, but there were places that adolescents could go for more information. There was a very big readership, so even if someone’s question wasn’t directly relevant to another adolescent, maybe the answer would be. And I have to say, in 23 years, I never used the same answer. It was just about being really sensitive and careful how I answered. Which was challenging to do when you’re not face to face with someone and you’ve only got 250 words.</Blog.Text>
            <br />
            <br />
            <Blog.Subtitle>~WORKING FOR DOLLY MAGAZINE~</Blog.Subtitle>
            <Blog.Text>Dolly Magazine, in my understanding of magazine media was considered the entry point for a lot of aspiring magazine writers and editors. The staff turnover was pretty high, and the staff was very young. I met lots of different people over the years. They only published five questions a month, for most of the years, and then they increased it to ten. For a few years they also published boys’ questions. There were never very many, but there was some. There was an editor that was there for the longest time. We had quite a good relationship in the sense that she was very keen to expand the health section in the magazine and look at what readers were really asking for. When I was working at the Children’s Hospital in adolescent medicine, I asked the editor if their staff might come and do a Dolly Day in the adolescent ward. We did that for a couple of years in a row. The staff would come and do makeovers and just chat to the kids in hospital. One year, they had one of their top male models come as well. That was a bit of a highlight. I had some really nice memorable times working for them. There was a particular era when the magazine was obviously doing really well. </Blog.Text>
            <Blog.Text>In the last five years as a magazine they started to become non-viable financially, like a lot of magazines really. They changed the model to save costs. They no longer wanted me as the medical consultant solely. They wanted to rotate the questions each month through panels of experts, including representatives from organizations like Beyond Blue. I think the problem was, I would have kept doing it for no money at all, but they couldn’t justify that. For the last couple of years, I was only answering questions every two months. I maintained a relationship with them right up until the end, but it was a pretty sad and sorry office the last time I visited, about two months before they shut down in December 2016. The number of questions they were receiving was drastically dropping. The whole thing was clearly dying.</Blog.Text>
            <br />
            <br />
            <Blog.Subtitle>~LESSONS LEARNED FROM THE LETTERS~</Blog.Subtitle>
            <Blog.Text>I have thousands of letters sitting in boxes at home, which is incredible. I ended up doing some qualitative research analysing the content readers were writing in about. The things that they were concerned about were not the sorts of things that they would go and talk to a doctor about. And often also not the sorts of things that would be taught about in standard sex education in schools.</Blog.Text>
            <Blog.Text>The thing is that as doctors, we may or may not even inquire about pubertal development. GPs may or may not ask about menarche in a girl. Whereas, to Dolly Doctor, there were questions about everything: breast development, breast symptoms, breast asymmetry, stretch marks, labia, pubic hair, acne, weight gain, physical growth in general; and then of course, a lot of questions about periods and vaginal secretions. A lot of them were tied into either body image, or concerns about sexual attractiveness. Most of the readers of Dolly Magazine were young and therefore not sexually active, but they were thinking about when they would become sexually active. The girls who were already having sex would often ask about the lack of orgasm and sometimes discomfort with penetrative sex. There was always a large proportion of questions about same sex attraction or believing that they were probably lesbian or gay, and a lot of questions about masturbation. I guess what it’s taught me is that I need to ask about these things in my clinical work. Of course only when it feels appropriate, but as a general question: “Are there any things about your puberty that worry you such as skin changes and breast development?” I think it’s good to put things out on the table and give patients the opportunity to ask about it if they want.</Blog.Text>
            <br />
            <br />
            <Blog.Subtitle>~ADVICE TO MEDCAL STUDENTS REGARDING ADOLESCENTS AND BEYOND~</Blog.Subtitle>
            <Blog.Text>Adolescence is a time of life that’s intense and private in lots of ways. I think it’s a real privilege if an adolescent takes us into their confidence. Also explaining and understanding the exceptions or boundaries around that is really important. I think the other thing is to be willing to have slightly stilted and slow conversations. I think we learn how to take histories really well in medicine that are around specific symptoms. It’s not always going to be that easy to get some of that information out of adolescent patients, particularly if they’re feeling very anxious or a bit angry about being there in the first place. It can be very, very challenging. Just learning to sit with a little bit of discomfort when there are silent pauses in conversation, or learning how to acknowledge that sense of awkwardness that might be in the room, is a positive step. I always say, if you can engage an adolescent in conversation within a medical consultation, you can engage anybody. It’s not because there’s anything wrong with them. It’s just that they’re learning how to be their own health advocates and their own health reporters, who have so far had their parents doing it for their whole lives. </Blog.Text>
            <Blog.Text>If you have any opportunity to talk to an adolescent on their own in your hospital placements, have a chat to them with their permission. Learn how to take a psychosocial history. Practice with them. Practice making confidentiality statements. It will benefit you. And any opportunity for a young person to have a private and confidential chat where someone who is genuinely interested in things other than their particular disease can benefit them too. The practice of medicine first and foremost is about humans. Every time you talk to a patient, relish and refine your skills in learning how to understand humans. I think that will stand you in good stead, whatever you end up doing.</Blog.Text>
        </Blog.TextBlock>
    )
}